### PR TITLE
Plugin update to make it work with IntelliJ 2020.3 until the latest 2022.1

### PR DESCRIPTION
**Pull request by wimsymons**
Some output from ./gradlew runPluginVerifier:

Plugin com.github.mateusz512.crxcleaner:0.0.5 against IC-212.5712.43: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.github.mateusz512.crxcleaner:0.0.5 against IC-213.7172.25: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.github.mateusz512.crxcleaner:0.0.5 against IC-221.5080.210: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.github.mateusz512.crxcleaner:0.0.5 against IC-203.8084.24: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.github.mateusz512.crxcleaner:0.0.5 against IC-211.7628.21: Compatible
    Plugin can be loaded/unloaded without IDE restart

### CODE REVIEW

**Comment by wimsymons** [comment]
Could you please update the IntelliJ Marketplace with a new release if you merge this? Thx!

**Comment by Mateusz512** [comment]
LGTM. Thanks for the contribution!

**Comment by wimsymons** [comment]
Thank you! Could you cut a new release 🙏 ?

**Comment by Mateusz512** [comment]
Pipeline is having some issues. I'll try fixing it tomorrow.

**Comment by wimsymons** [comment]
@Mateusz512 maybe this helps to get the pipeline working again? https://tomgregory.com/build-gradle-projects-with-github-actions/#6_Use_gradle-build-action

**Comment by Mateusz512** [comment]
@wimsymons nope, that was not it, but thanks anyway :D 

v0.0.5 is pending release on plugin marketplace. Should be available within a day or two.

**Pull request merged**
